
STATUS_NEW = 'new'
STATUS_IN_PROGRESS = 'inProgress'
STATUS_CLOSED = 'closed'
STATUS_DELETED = 'deleted'

STATUS_CHOICES = (
    (STATUS_NEW, STATUS_NEW),
    (STATUS_IN_PROGRESS, STATUS_IN_PROGRESS),
    (STATUS_CLOSED, STATUS_CLOSED),
    (STATUS_DELETED, STATUS_DELETED),
)
